// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRijEFuNEdWPjL_j9EiT4bdgovAgkAMXk',
    appId: '1:231160723385:web:a07a19fef566167ccc6868',
    messagingSenderId: '231160723385',
    projectId: 'beginners-course-demo',
    authDomain: 'beginners-course-demo.firebaseapp.com',
    storageBucket: 'beginners-course-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbgy7InCKt-TdXQ32pkbg3FfF9tKDpc94',
    appId: '1:231160723385:android:ee4d04dd2715d322cc6868',
    messagingSenderId: '231160723385',
    projectId: 'beginners-course-demo',
    storageBucket: 'beginners-course-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gmgcmFsoq9EK9WJ6IIL_kpNYbBZ7MjI',
    appId: '1:231160723385:ios:9dfd39b5c6d6afeacc6868',
    messagingSenderId: '231160723385',
    projectId: 'beginners-course-demo',
    storageBucket: 'beginners-course-demo.appspot.com',
    iosBundleId: 'com.example.beginnersCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gmgcmFsoq9EK9WJ6IIL_kpNYbBZ7MjI',
    appId: '1:231160723385:ios:4bf81cfe55318dfacc6868',
    messagingSenderId: '231160723385',
    projectId: 'beginners-course-demo',
    storageBucket: 'beginners-course-demo.appspot.com',
    iosBundleId: 'com.example.beginnersCourse.RunnerTests',
  );
}
